### ISSUE TITLE
Update example to newest material-ui version

### ISSUE THREAD

**Issue by tomyitav** [alexanmtz/material-sense#2]
Hi @alexanmtz , thanks for sharing this awesome project!
Wondered if you could update the example for the newest material-ui api.
Thanks!

**Comment by alexanmtz** [comment]
Hello @tomyitav , thanks for let me know. It would be nice to update, cause it's really hard to maintain after some time outdated. I'm really facing some issues in another project that I need to update to the newest material ui, so I can do on this project afterwards. But if you wish, you can update and send me a Pull Request and contribute with this project, what you think?

**Comment by tomsaleeba** [comment]
@tomyitav I've just sent a PR for this issue: https://github.com/alexanmtz/material-sense/pull/3. See if it's what you're after. I'm still a React n00b so sorry if I've broken something.

**Comment by alexanmtz** [comment]
@tomsaleeba I approved your PR because you made a lot of minor fixes and improvements and thanks for the great work, but to actually update the Material UI we need to change to the newest version on `package.json`, feel free to update, run yarn and test and send another PR with this purpose if you want to contribute once more 👍

**Comment by tomsaleeba** [comment]
I didn't update the package.json file but because you used the leading caret (`^`), just running the `yarn upgrade` brought the lock file up to latest @material-ui/core:
https://github.com/alexanmtz/material-sense/commit/72a8448e8c2e11010cbb68ba12bca9a0b562dca8#diff-8ee2343978836a779dc9f8d6b794c3b2R883

Happy to explicitly update the package.json if still want.

**Comment by alexanmtz** [comment]
You're right @tomsaleeba, so let's consider this done 🚀

We can make it explicit when we update to a major version, but in this case, this solution is good 👍 

Can you check it now that is merged @tomyitav ?

**Comment by tomsaleeba** [comment]
:+1: happy to help
